version: 2
sources:
  - name: dwh_meta
    database: flights_dw
    schema: dwh_meta
    tables:
      - name: _dwh_watermarks
        description: "Stores high-watermark timestamps for ETL loading processes."
        columns:
          - name: table_name
            description: "The name of the table the watermark applies to."
            tests:
              - unique
              - not_null
          - name: last_inserted_at
            description: "The latest _inserted_at timestamp successfully loaded for this table."

  - name: gold_layer
    database: flights_dw
    schema: gold
    tables:
      # --- DIMENSION TABLES ---

      - name: dim_aircrafts
        description: "Dimension table for individual aircraft, identified by their registration."
        columns:
          - name: aircraft_sk
            description: "Surrogate primary key for the aircraft."
            tests:
              - unique
              - not_null
          - name: aircraft_reg
            description: "The unique aircraft registration number (e.g., tail number)."
          - name: aircraft_mode_s
            description: "The unique ICAO 24-bit address for the aircraft."
          - name: aircraft_model
            description: "The model of the aircraft (e.g., 'Boeing 737-800')."
          - name: aircraft_sk_type
            description: "The type of aircraft."
          - name: _ingested_at
            description: "Timestamp of initial ingestion."
          - name: _inserted_at
            description: "Timestamp of insertion into this dimension table."
            tests:
              - not_null

      - name: dim_airlines
        description: "Dimension table for commercial airlines."
        columns:
          - name: airline_sk
            description: "Surrogate primary key for the airline."
            tests:
              - unique
              - not_null
          - name: airline_iata
            description: "The 2-letter IATA code for the airline (e.g., 'FR')."
          - name: airline_icao
            description: "The 3-letter ICAO code for the airline (e.g., 'RYR')."
          - name: airline_name
            description: "The common name of the airline (e.g., 'Ryanair')."
          - name: _ingested_at
            description: "Timestamp of initial ingestion."
          - name: _inserted_at
            description: "Timestamp of insertion into this dimension table."
            tests:
              - not_null

      - name: dim_airports
        description: "Dimension table for airports."
        columns:
          - name: airport_sk
            description: "Surrogate primary key for the airport."
            tests:
              - unique
              - not_null
          - name: airport_iata
            description: "The 3-letter IATA code for the airport."
          - name: airport_icao
            description: "The 4-letter ICAO code for the airport."
          - name: airport_name
            description: "The common name of the airport."
          - name: municipality_name
            description: "The city or municipality where the airport is located."
          - name: country_name
            description: "The country where the airport is located."
          - name: continent_name
            description: "The continent where the airport is located."
          - name: latitude
            description: "The latitude of the airport."
          - name: longitude
            description: "The longitude of the airport."
          - name: elevation_feet
            description: "The elevation of the airport in feet."
          - name: airport_time_zone
            description: "The IANA time zone of the airport (e.g., 'Europe/Paris')."
          - name: _ingested_at
            description: "Timestamp of initial ingestion."
          - name: _inserted_at
            description: "Timestamp of insertion into this dimension table."
            tests:
              - not_null

      - name: dim_quality_combination
        description: "Dimension describing the combination of data quality levels for a flight's departure and arrival data."
        columns:
          - name: quality_combo_sk
            description: "Surrogate primary key for the quality combination."
            tests:
              - unique
              - not_null
          - name: dep_has_basic
            description: "Flag indicating if basic departure data is available."
          - name: dep_has_live
            description: "Flag indicating if live departure data is available."
          - name: arr_has_basic
            description: "Flag indicating if basic arrival data is available."
          - name: arr_has_live
            description: "Flag indicating if live arrival data is available."
          - name: quality_desc
            description: "A text description of the quality combination."
          - name: _ingested_at
            description: "Timestamp of initial ingestion."
          - name: _inserted_at
            description: "Timestamp of insertion into this dimension table."
            tests:
              - not_null

      - name: dim_flight_details
        description: "Dimension table describing the status and type of a flight."
        columns:
          - name: flight_details_sk
            description: "Surrogate primary key for the flight details dimension."
            tests:
              - unique
              - not_null
          - name: flight_status
            description: "The status of the flight (e.g., Landed, Canceled, Active)."
          - name: codeshare_status
            description: "The codeshare status of the flight."
          - name: is_cargo
            description: "Flag indicating if the flight is a cargo flight."
          - name: _ingested_at
            description: "Timestamp when the record was first ingested."
          - name: _inserted_at
            description: "Timestamp when the record was inserted into this table."
            tests:
              - not_null

      - name: dim_runways
        description: "Dimension table for airport runways. Modeled as a Type 2 Slowly Changing Dimension to track changes over time."
        columns:
          - name: runway_version_key
            description: "Primary key for a specific version of a runway. Handles changes over time."
            tests:
              - unique
              - not_null
          - name: runway_sk
            description: "Surrogate key that remains constant for a runway across all its versions."
          - name: airport_sk
            description: "Foreign key to the dim_airports table."
            tests:
              # This is the dbt equivalent of a Foreign Key constraint check.
              - relationships:
                  to: source('gold_layer', 'dim_airports')
                  field: airport_sk
          - name: runway_name
            description: "The name of the runway (e.g., '08L/26R')."
          - name: true_heading
            description: "The true heading of the runway."
          - name: surface
            description: "The surface material of the runway (e.g., 'ASPH')."
          - name: has_lighting
            description: "Flag indicating if the runway has lighting."
          - name: is_closed
            description: "Flag indicating if the runway is closed."
          - name: length_feet
            description: "The length of the runway in feet."
          - name: width_feet
            description: "The width of the runway in feet."
          - name: displaced_threshold_feet
            description: "The length of the displaced threshold in feet."
          - name: latitude
            description: "The latitude of the runway's center point."
          - name: longitude
            description: "The longitude of the runway's center point."
          - name: effective_start_date
            description: "The date this version of the runway record became effective."
          - name: effective_end_date
            description: "The date this version of the runway record was superseded."
          - name: _ingested_at
            description: "Timestamp of initial ingestion."
          - name: _inserted_at
            description: "Timestamp of insertion into this dimension table."
            tests:
              - not_null


      # --- FACT TABLES ---
      - name: fct_flights_intermediate
        description: "Partitioned source table containing raw flight facts, loaded by the Python ETL."
        columns:
          - name: fact_flight_id
            description: "Surrogate primary key for the flight fact record."
            tests:
              - unique
              - not_null
          - name: flight_composite_pk
            description: "Natural key for the flight event."
            tests:
              - unique
              - not_null
          - name: flight_details_sk
            description: "Foreign key to dim_flight_details."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_flight_details')
                  field: flight_details_sk
          - name: departure_airport_sk
            description: "Foreign key to dim_airports for departure."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_airports')
                  field: airport_sk
          - name: arrival_airport_sk
            description: "Foreign key to dim_airports for arrival."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_airports')
                  field: airport_sk
          - name: airline_sk
            description: "Foreign key to dim_airlines."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_airlines')
                  field: airline_sk
          - name: aircraft_sk
            description: "Foreign key to dim_aircrafts."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_aircrafts')
                  field: aircraft_sk
          - name: departure_runway_version_key
            description: "Foreign key to dim_runways for departure."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_runways')
                  field: runway_version_key
          - name: arrival_runway_version_key
            description: "Foreign key to dim_runways for arrival."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_runways')
                  field: runway_version_key
          - name: quality_combo_sk
            description: "Foreign key to dim_quality_combination."
            tests:
              - relationships:
                  to: source('gold_layer', 'dim_quality_combination')
                  field: quality_combo_sk
          - name: flight_number
          - name: flight_callsign
          - name: dep_terminal
          - name: arr_gate
          - name: dep_checkin_desk
          - name: dep_gate
          - name: arr_terminal
          - name: arr_baggage_belt
          - name: dep_local_timezone
          - name: arr_local_timezone
          - name: dep_scheduled_at_utc
          - name: dep_revised_at_utc
          - name: dep_runway_at_utc
          - name: arr_scheduled_at_utc
          - name: arr_revised_at_utc
          - name: arr_runway_at_utc
          - name: last_location_reported_at_utc
          - name: latitude
          - name: longitude
          - name: altitude_ft
          - name: ground_speed_kts
          - name: true_track_deg
          - name: ingestion_hour
          - name: _ingested_at
          - name: _inserted_at
            tests:
              - not_null
          - name: flight_date
            description: "The date of the flight, used for partitioning the table."
            tests:
              - not_null


# =================================================================
# PART 2: MODELS
# Describes the tables/views created by your dbt .sql files.
# =================================================================
models:
  - name: dim_dates
    description: "A static dimension table containing a record for each date, enriched with calendar attributes."
    columns:
      - name: date_key
        description: "The primary key for the date dimension (format YYYYMMDD)."
        tests:
          - unique
          - not_null
      - name: full_date
        description: "The full date (e.g., '2025-06-01')."
        tests:
          - unique
          - not_null
      - name: day_of_month
      - name: day_name
      - name: day_of_week_iso
      - name: day_of_year
      - name: week_of_year
      - name: month_of_year
      - name: month_name
      - name: quarter_of_year
      - name: year
      - name: is_weekend

  - name: fct_flights_final
    description: "Final, enriched fact table for flights. This model joins all dimension keys and adds calculated measures like delays and durations."
    columns:
      - name: fact_flight_id
        description: "The unique surrogate primary key for the fact table."
        tests:
          - unique
          - not_null

      - name: flight_composite_pk
        description: "The natural key of the flight event."
        tests:
          - unique
          - not_null

      - name: flight_details_sk
        description: "Foreign key to the flight details dimension."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_flight_details')
              field: flight_details_sk

      - name: departure_airport_sk
        description: "Foreign key to the airports dimension for the departure airport."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_airports')
              field: airport_sk

      - name: arrival_airport_sk
        description: "Foreign key to the airports dimension for the arrival airport."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_airports')
              field: airport_sk

      - name: airline_sk
        description: "Foreign key to the airlines dimension."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_airlines')
              field: airline_sk

      - name: aircraft_sk
        description: "Foreign key to the aircraft dimension."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_aircrafts')
              field: aircraft_sk

      - name: departure_runway_version_key
        description: "Foreign key to the runways dimension for the departure runway version."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_runways')
              field: runway_version_key

      - name: arrival_runway_version_key
        description: "Foreign key to the runways dimension for the arrival runway version."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_runways')
              field: runway_version_key

      - name: quality_combo_sk
        description: "Foreign key to the data quality dimension."
        tests:
          - relationships:
              to: source('gold_layer', 'dim_quality_combination')
              field: quality_combo_sk
              
      - name: departure_date_key
        description: "Foreign key to the date dimension for the departure date."
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key

      - name: arrival_date_key
        description: "Foreign key to the date dimension for the arrival date."
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key

      - name: flight_number
        description: "The flight number (e.g., 'FR 2506')."
      - name: flight_callsign
        description: "The flight callsign used for ATC communication."
      - name: dep_terminal
        description: "Departure terminal."
      - name: arr_gate
        description: "Arrival gate."
      - name: dep_checkin_desk
        description: "Departure check-in desk."
      - name: dep_gate
        description: "Departure gate."
      - name: arr_terminal
        description: "Arrival terminal."
      - name: arr_baggage_belt
        description: "Arrival baggage belt."
      - name: dep_local_timezone
        description: "Departure airport's local timezone (e.g., '+02:00')."
      - name: arr_local_timezone
        description: "Arrival airport's local timezone (e.g., '+01:00')."
      - name: dep_scheduled_at_utc
        description: "Scheduled departure time in UTC."
      - name: dep_revised_at_utc
        description: "Revised departure time in UTC."
      - name: dep_runway_at_utc
        description: "Actual time the aircraft left the runway for departure in UTC."
      - name: arr_scheduled_at_utc
        description: "Scheduled arrival time in UTC."
      - name: arr_revised_at_utc
        description: "Revised arrival time in UTC."
      - name: arr_runway_at_utc
        description: "Actual time the aircraft reached the runway on arrival in UTC."
      - name: last_location_reported_at_utc
        description: "The last timestamp a location update was received in UTC."
      - name: latitude
        description: "Last reported latitude."
      - name: longitude
        description: "Last reported longitude."
      - name: altitude_ft
        description: "Last reported altitude in feet."
      - name: ground_speed_kts
        description: "Last reported ground speed in knots."
      - name: true_track_deg
        description: "Last reported true track in degrees."
      - name: ingestion_hour
        description: "The hour of the day the data was ingested (YYYY-MM-DD-HH)."
      - name: _ingested_at
        description: "Timestamp when the record was first ingested into the system."
      - name: _inserted_at
        description: "Timestamp when the record was inserted into this table by dbt."
        tests:
          - not_null
      - name: flight_date
        description: "The date of the flight."
        tests:
          - not_null