"""add dep_runway_name and arr_runway_name to stg.flights

Revision ID: 01a9da62f6b6
Revises: 2af719b0923d
Create Date: 2025-11-13 11:10:05.230005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a9da62f6b6'
down_revision: Union[str, Sequence[str], None] = '2af719b0923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('flights', sa.Column('dep_runway_name', sa.String(length=50), nullable=True), schema='stg')
    op.add_column('flights', sa.Column('arr_runway_name', sa.String(length=50), nullable=True), schema='stg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'arr_runway_name', schema='stg')
    op.drop_column('flights', 'dep_runway_name', schema='stg')
    # ### end Alembic commands ###
