"""initial schema creation

Revision ID: b5e88364425d
Revises: 
Create Date: 2025-11-10 09:38:13.201434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e88364425d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS stg;")
    op.execute("CREATE SCHEMA IF NOT EXISTS dwh_meta;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_dwh_watermarks',
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('last_inserted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('table_name'),
    schema='dwh_meta'
    )
    op.create_table('dim_aircrafts',
    sa.Column('aircraft_bk', sa.Text(), nullable=False),
    sa.Column('aircraft_reg', sa.String(length=50), nullable=True),
    sa.Column('aircraft_mode_s', sa.String(length=50), nullable=True),
    sa.Column('aircraft_model', sa.String(length=255), nullable=True),
    sa.Column('aircraft_bk_type', sa.String(length=255), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('aircraft_bk'),
    schema='stg'
    )
    op.create_table('dim_airlines',
    sa.Column('airline_bk', sa.Text(), nullable=False),
    sa.Column('airline_iata', sa.String(length=10), nullable=True),
    sa.Column('airline_icao', sa.String(length=10), nullable=True),
    sa.Column('airline_name', sa.String(length=255), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('airline_bk'),
    schema='stg'
    )
    op.create_table('dim_airports',
    sa.Column('airport_bk', sa.CHAR(length=64), nullable=False),
    sa.Column('iso_region', sa.String(length=128), nullable=True),
    sa.Column('iso_country', sa.String(length=2), nullable=True),
    sa.Column('airport_iata', sa.String(length=10), nullable=True),
    sa.Column('airport_icao', sa.String(length=10), nullable=True),
    sa.Column('airport_gps', sa.String(length=255), nullable=True),
    sa.Column('airport_local_code', sa.String(length=50), nullable=True),
    sa.Column('airport_name', sa.String(length=255), nullable=True),
    sa.Column('municipality_name', sa.String(length=255), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('continent_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('elevation_feet', sa.Double(), nullable=True),
    sa.Column('airport_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_service', sa.String(length=10), nullable=True),
    sa.Column('airport_time_zone', sa.String(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('airport_bk'),
    schema='stg'
    )
    op.create_table('dim_regions',
    sa.Column('region_code', sa.String(length=128), nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=True),
    sa.Column('local_code', sa.String(length=50), nullable=True),
    sa.Column('continent_code', sa.String(length=2), nullable=True),
    sa.Column('iso_country', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('region_code'),
    schema='stg'
    )
    op.create_table('dim_runways',
    sa.Column('runway_version_bk', sa.Text(), nullable=False),
    sa.Column('runway_bk', sa.Text(), nullable=False),
    sa.Column('airport_bk', sa.CHAR(length=64), nullable=False),
    sa.Column('runway_name', sa.String(), nullable=True),
    sa.Column('true_heading', sa.Double(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('has_lighting', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('length_feet', sa.Double(), nullable=True),
    sa.Column('width_feet', sa.Double(), nullable=True),
    sa.Column('displaced_threshold_feet', sa.Double(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('elevation_feet', sa.Double(), nullable=True),
    sa.Column('runway_end_type', sa.String(), nullable=True),
    sa.Column('effective_start_date', sa.DateTime(), nullable=True),
    sa.Column('effective_end_date', sa.DateTime(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('runway_version_bk'),
    schema='stg'
    )
    op.create_index(op.f('ix_stg_dim_runways_airport_bk'), 'dim_runways', ['airport_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_dim_runways_runway_bk'), 'dim_runways', ['runway_bk'], unique=False, schema='stg')
    op.create_table('fct_flights_intermediate',
    sa.Column('fact_flight_id', sa.BigInteger(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('flight_composite_pk', sa.Text(), nullable=False),
    sa.Column('departure_airport_bk', sa.CHAR(length=64), nullable=True),
    sa.Column('arrival_airport_bk', sa.CHAR(length=64), nullable=True),
    sa.Column('airline_bk', sa.Text(), nullable=True),
    sa.Column('aircraft_bk', sa.Text(), nullable=True),
    sa.Column('departure_runway_version_bk', sa.Text(), nullable=True),
    sa.Column('arrival_runway_version_bk', sa.Text(), nullable=True),
    sa.Column('flight_number', sa.Text(), nullable=True),
    sa.Column('flight_callsign', sa.Text(), nullable=True),
    sa.Column('flight_status', sa.Text(), nullable=True),
    sa.Column('codeshare_status', sa.Text(), nullable=True),
    sa.Column('is_cargo', sa.Boolean(), nullable=True),
    sa.Column('dep_terminal', sa.Text(), nullable=True),
    sa.Column('arr_gate', sa.Text(), nullable=True),
    sa.Column('dep_checkin_desk', sa.Text(), nullable=True),
    sa.Column('dep_gate', sa.Text(), nullable=True),
    sa.Column('arr_terminal', sa.Text(), nullable=True),
    sa.Column('arr_baggage_belt', sa.Text(), nullable=True),
    sa.Column('dep_local_timezone', sa.Text(), nullable=True),
    sa.Column('arr_local_timezone', sa.Text(), nullable=True),
    sa.Column('dep_has_basic', sa.Boolean(), nullable=True),
    sa.Column('dep_has_live', sa.Boolean(), nullable=True),
    sa.Column('arr_has_basic', sa.Boolean(), nullable=True),
    sa.Column('arr_has_live', sa.Boolean(), nullable=True),
    sa.Column('quality_desc', sa.Text(), nullable=True),
    sa.Column('dep_scheduled_at_utc', sa.DateTime(), nullable=True),
    sa.Column('dep_revised_at_utc', sa.DateTime(), nullable=True),
    sa.Column('dep_runway_at_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_scheduled_at_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_revised_at_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_runway_at_utc', sa.DateTime(), nullable=True),
    sa.Column('last_location_reported_at_utc', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('altitude_ft', sa.Double(), nullable=True),
    sa.Column('ground_speed_kts', sa.Double(), nullable=True),
    sa.Column('true_track_deg', sa.Double(), nullable=True),
    sa.Column('ingestion_hour', sa.Text(), nullable=True),
    sa.Column('_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('_inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('fact_flight_id', 'flight_date'),
    sa.UniqueConstraint('flight_composite_pk'),
    schema='stg'
    )
    op.create_index(op.f('ix_stg_fct_flights_intermediate_aircraft_bk'), 'fct_flights_intermediate', ['aircraft_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_fct_flights_intermediate_airline_bk'), 'fct_flights_intermediate', ['airline_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_fct_flights_intermediate_arrival_airport_bk'), 'fct_flights_intermediate', ['arrival_airport_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_fct_flights_intermediate_arrival_runway_version_bk'), 'fct_flights_intermediate', ['arrival_runway_version_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_fct_flights_intermediate_departure_airport_bk'), 'fct_flights_intermediate', ['departure_airport_bk'], unique=False, schema='stg')
    op.create_index(op.f('ix_stg_fct_flights_intermediate_departure_runway_version_bk'), 'fct_flights_intermediate', ['departure_runway_version_bk'], unique=False, schema='stg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_departure_runway_version_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_departure_airport_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_arrival_runway_version_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_arrival_airport_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_airline_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_fct_flights_intermediate_aircraft_bk'), table_name='fct_flights_intermediate', schema='stg')
    op.drop_table('fct_flights_intermediate', schema='stg')
    op.drop_index(op.f('ix_stg_dim_runways_runway_bk'), table_name='dim_runways', schema='stg')
    op.drop_index(op.f('ix_stg_dim_runways_airport_bk'), table_name='dim_runways', schema='stg')
    op.drop_table('dim_runways', schema='stg')
    op.drop_table('dim_regions', schema='stg')
    op.drop_table('dim_airports', schema='stg')
    op.drop_table('dim_airlines', schema='stg')
    op.drop_table('dim_aircrafts', schema='stg')
    op.drop_table('_dwh_watermarks', schema='dwh_meta')
    # ### end Alembic commands ###
